# doom-ayu-mirage-dark theme for iamb
#
# You can place this directly in your `~/.config/iamb/themes` directory to make it
# discoverable, or copy its contents directly into your `config.toml`.
#
# If you are looking to remix this file to make a derived theme, the colors were
# picked and assigned as:
#
# COLOR_BG1 => Primary background (#272D38)
# COLOR_BG2 => Alternate background (#242B38)
# COLOR_BG3 => Completion menu selected item background (#D9D7CE)
#
# COLOR_UI1 => Window border color, text completion menu (#3D4751)
# COLOR_UI2 => Window title color (#FFCC66)
#
# COLOR_WARN1 => Errors, unencrypted, etc. - typically a red (#FFAE57)
# COLOR_WARN2 => Redacted messages - typically a red or light orange (#5C6773)
# COLOR_WARN3 => Unknown encryption status - typically a yellow (#FFC44C)
#
# COLOR_GOOD1 => Encrypted indicator - typically a green (#BBE67E)
#
# COLOR_TEXT1 => Primary text color (#FFD57F)
# COLOR_TEXT2 => Contrast text color, should differ from COLOR_TEXT1 (#E0E2EA)
# COLOR_TEXT3 => Alternate text color (#80D4FF)
# COLOR_TEXT4 => Alternate text color (#D4BFFF)
# COLOR_TEXT5 => Alternate text color (#5CCFE6)
#
[theme.users]
colors = [
    "#FFAE57",
    "#5C6773",
    "#FFC44C",
    "#BBE67E",
    "#E0E2EA",
    "#80D4FF",
    "#D4BFFF",
    "#5CCFE6",
]

[theme.default]
color = "#FFD57F"
background = "#272D38"

[theme.completion]
default.background = "#D9D7CE"
default.color = "#3D4751"
selected.background = "#242B38"
selected.color = "#FFD57F"

[theme.timeline]
redacted.color = "#5C6773"

[theme.messages]
code.color = "#E0E2EA"
code.background = "#242B38"
emphasis.color = "#D4BFFF"
strong.color = "#80D4FF"

[theme.rooms]
default.color = "#5CCFE6"
unread.color = "#E0E2EA"
labels.color = "#D4BFFF"

[theme.windows]
border.color = "#3D4751"
title.color = "#FFCC66"

[theme.encryption]
icon_encrypted.color = "#BBE67E"
icon_unencrypted.color = "#FFAE57"
icon_unknown.color = "#FFC44C"

[theme.cmdbar]
error.color = "#FFAE57"
