# catppuccin-light theme for iamb
#
# You can place this directly in your `~/.config/iamb/themes` directory to make it
# discoverable, or copy its contents directly into your `config.toml`.
#
# If you are looking to remix this file to make a derived theme, the colors were
# picked and assigned as:
#
# COLOR_BG1 => Primary background (#EFF1F5)
# COLOR_BG2 => Alternate background (#E9EBF1)
# COLOR_BG3 => Completion menu selected item background (#E6E9EF)
#
# COLOR_UI1 => Window border color, text completion menu (#BCC0CC)
# COLOR_UI2 => Window title color (#8839EF)
#
# COLOR_WARN1 => Errors, unencrypted, etc. - typically a red (#FE640B)
# COLOR_WARN2 => Redacted messages - typically a red or light orange (#DD7878)
# COLOR_WARN3 => Unknown encryption status - typically a yellow (#7C7F93)
#
# COLOR_GOOD1 => Encrypted indicator - typically a green (#40A02B)
#
# COLOR_TEXT1 => Primary text color (#4C4F69)
# COLOR_TEXT2 => Contrast text color, should differ from COLOR_TEXT1 (#1E66F5)
# COLOR_TEXT3 => Alternate text color (#7287FD)
# COLOR_TEXT4 => Alternate text color (#EA76CB)
# COLOR_TEXT5 => Alternate text color (#04A5E5)
#
[theme.users]
colors = [
    # Latte
    "#04A5E5",
    "#179299",
    "#1E66F5",
    "#209FB5",
    "#40A02B",
    "#4C4F69",
    "#5C5F77",
    "#6C6F85",
    "#7287FD",
    "#7C7F93",
    "#8839EF",
    "#8C8FA1",
    "#9CA0B0",
    "#ACB0BE",
    "#BCC0CC",
    "#D20F39",
    "#DC8A78",
    "#DD7878",
    "#DF8E1D",
    "#E64553",
    "#EA76CB",
    "#FE640B",
    
    # Frappé
    "#232634",
    "#292C3C",
    "#303446",
    "#414559",
    "#51576D",
    "#626880",
    "#737994",
    "#81C8BE",
    "#838BA7",
    "#85C1DC",
    "#8CAAEE",
    "#949CBB",
    "#99D1DB",
    "#A5ADCE",
    "#A6D189",
    "#B5BFE2",
    "#BABBF1",
    "#C6D0F5",
    "#CA9EE6",
    "#E5C890",
    "#E78284",
    "#EA999C",
    "#EEBEBE",
    "#EF9F76",
    "#F4B8E4",

    # Macchiato
    "#181926",
    "#1E2030",
    "#24273A",
    "#363A4F",
    "#494D64",
    "#5B6078",
    "#6E738D",
    "#7DC4E4",
    "#8087A2",
    "#8AADF4",
    "#8BD5CA",
    "#91D7E3",
    "#939AB7",
    "#A5ADCB",
    "#A6DA95",
    "#B7BDF8",
    "#B8C0E0",
    "#C6A0F6",
    "#CAD3F5",
    "#ED8796",
    "#EE99A0",
    "#EED49F",
    "#F0C6C6",
    "#F5A97F",
    "#F5BDE6",

    # Mocha
    "#11111B",
    "#181825",
    "#1E1E2E",
    "#313244",
    "#45475A",
    "#585B70",
    "#6C7086",
    "#74C7EC",
    "#7F849C",
    "#89B4FA",
    "#89DCEB",
    "#9399B2",
    "#94E2D5",
    "#A6ADC8",
    "#A6E3A1",
    "#B4BEFE",
    "#BAC2DE",
    "#CBA6F7",
    "#CDD6F4",
    "#EBA0AC",
    "#F2CDCD",
    "#F38BA8",
    "#F5C2E7",
    "#FAB387",
]

[theme.default]
color = "#4C4F69"
background = "#EFF1F5"

[theme.completion]
default.background = "#E6E9EF"
default.color = "#BCC0CC"
selected.background = "#E9EBF1"
selected.color = "#4C4F69"

[theme.timeline]
redacted.color = "#DD7878"

[theme.messages]
code.color = "#1E66F5"
code.background = "#E9EBF1"
emphasis.color = "#EA76CB"
strong.color = "#7287FD"

[theme.rooms]
default.color = "#04A5E5"
unread.color = "#1E66F5"
labels.color = "#EA76CB"

[theme.windows]
border.color = "#BCC0CC"
title.color = "#8839EF"

[theme.encryption]
icon_encrypted.color = "#40A02B"
icon_unencrypted.color = "#FE640B"
icon_unknown.color = "#7C7F93"

[theme.cmdbar]
error.color = "#FE640B"
