# jellybeans-muted-dark theme for iamb
#
# You can place this directly in your `~/.config/iamb/themes` directory to make it
# discoverable, or copy its contents directly into your `config.toml`.
#
# If you are looking to remix this file to make a derived theme, the colors were
# picked and assigned as:
#
# COLOR_BG1 => Primary background (#101010)
# COLOR_BG2 => Alternate background (#1C1C1C)
# COLOR_BG3 => Completion menu selected item background (#1E1E1C)
#
# COLOR_UI1 => Window border color, text completion menu (#83ADC3)
# COLOR_UI2 => Window title color (#DAD6C8)
#
# COLOR_WARN1 => Errors, unencrypted, etc. - typically a red (#C88A77)
# COLOR_WARN2 => Redacted messages - typically a red or light orange (#7A7A7A)
# COLOR_WARN3 => Unknown encryption status - typically a yellow (#58534F)
#
# COLOR_GOOD1 => Encrypted indicator - typically a green (#909C6E)
#
# COLOR_TEXT1 => Primary text color (#F9F5EC)
# COLOR_TEXT2 => Contrast text color, should differ from COLOR_TEXT1 (#EACE98)
# COLOR_TEXT3 => Alternate text color (#A6C3D9)
# COLOR_TEXT4 => Alternate text color (#C2BDB8)
# COLOR_TEXT5 => Alternate text color (#B8AED3)
#
# COLOR_PLUS => Extra user colors used for users: "#617B87"
[theme.users]
colors = [
    "#C88A77",
    "#7A7A7A",
    "#58534F",
    "#909C6E",
    "#EACE98",
    "#A6C3D9",
    "#C2BDB8",
    "#B8AED3",
    "#617B87"
]

[theme.default]
color = "#F9F5EC"
background = "#101010"

[theme.completion]
default.background = "#1E1E1C"
default.color = "#83ADC3"
selected.background = "#1C1C1C"
selected.color = "#F9F5EC"

[theme.timeline]
redacted.color = "#7A7A7A"

[theme.messages]
code.color = "#EACE98"
code.background = "#1C1C1C"
emphasis.color = "#C2BDB8"
strong.color = "#A6C3D9"

[theme.rooms]
default.color = "#B8AED3"
unread.color = "#EACE98"
labels.color = "#C2BDB8"

[theme.windows]
border.color = "#83ADC3"
title.color = "#DAD6C8"

[theme.encryption]
icon_encrypted.color = "#909C6E"
icon_unencrypted.color = "#C88A77"
icon_unknown.color = "#58534F"

[theme.cmdbar]
error.color = "#C88A77"
