# base16-solarized-light-light theme for iamb
#
# You can place this directly in your `~/.config/iamb/themes` directory to make it
# discoverable, or copy its contents directly into your `config.toml`.
#
# If you are looking to remix this file to make a derived theme, the colors were
# picked and assigned as:
#
# COLOR_BG1 => Primary background (#FDF6E3)
# COLOR_BG2 => Alternate background (#EEE8D5)
# COLOR_BG3 => Completion menu selected item background (#93A1A1)
#
# COLOR_UI1 => Window border color, text completion menu (#2AA198)
# COLOR_UI2 => Window title color (#6C71C4)
#
# COLOR_WARN1 => Errors, unencrypted, etc. - typically a red (#DC322F)
# COLOR_WARN2 => Redacted messages - typically a red or light orange (#CB4B16)
# COLOR_WARN3 => Unknown encryption status - typically a yellow (#839496)
#
# COLOR_GOOD1 => Encrypted indicator - typically a green (#859900)
#
# COLOR_TEXT1 => Primary text color (#D33682)
# COLOR_TEXT2 => Contrast text color, should differ from COLOR_TEXT1 (#268BD2)
# COLOR_TEXT3 => Alternate text color (#586E75)
# COLOR_TEXT4 => Alternate text color (#657B83)
# COLOR_TEXT5 => Alternate text color (#D33682)
#
# COLOR_PLUS => Extra user colors used for users: 
[theme.users]
colors = [
    "#DC322F",
    "#CB4B16",
    "#839496",
    "#859900",
    "#268BD2",
    "#586E75",
    "#657B83",
    "#D33682",
    
]

[theme.default]
color = "#D33682"
background = "#FDF6E3"

[theme.completion]
default.background = "#93A1A1"
default.color = "#2AA198"
selected.background = "#EEE8D5"
selected.color = "#D33682"

[theme.timeline]
redacted.color = "#CB4B16"

[theme.messages]
code.color = "#268BD2"
code.background = "#EEE8D5"
emphasis.color = "#657B83"
strong.color = "#586E75"

[theme.rooms]
default.color = "#D33682"
unread.color = "#268BD2"
labels.color = "#657B83"

[theme.windows]
border.color = "#2AA198"
title.color = "#6C71C4"

[theme.encryption]
icon_encrypted.color = "#859900"
icon_unencrypted.color = "#DC322F"
icon_unknown.color = "#839496"

[theme.cmdbar]
error.color = "#DC322F"
