# tokyonight-dark theme for iamb
#
# You can place this directly in your `~/.config/iamb/themes` directory to make it
# discoverable, or copy its contents directly into your `config.toml`.

#
# If you are looking to remix this file to make a derived theme, the colors were
# picked and assigned as:
#
# COLOR_BG1 => Primary background (#1F2335)
# COLOR_BG2 => Alternate background (#24283B)
# COLOR_BG3 => Completion menu selected item background (#292E42)
#
# COLOR_UI1 => Window border color, text completion menu (#3B4261)
# COLOR_UI2 => Window title color (#C0CAF5)
#
# COLOR_WARN1 => Errors, unencrypted, etc. - typically a red (#FF8349)
# COLOR_WARN2 => Redacted messages - typically a red or light orange (#737AA2)
# COLOR_WARN3 => Unknown encryption status - typically a yellow (#2AC3DE)
#
# COLOR_GOOD1 => Encrypted indicator - typically a green (#9ECE6A)
#
# COLOR_TEXT1 => Primary text color (#89DDFF)
# COLOR_TEXT2 => Contrast text color, should differ from COLOR_TEXT1 (#A9B1D6)
# COLOR_TEXT3 => Alternate text color (#BB9AF7)
# COLOR_TEXT4 => Alternate text color (#7AA2F7)
# COLOR_TEXT5 => Alternate text color (#565F89)
#
# COLOR_PLUS => Extra user colors used for users: 
[theme.users]
colors = [
    "#FF8349",
    "#737AA2",
    "#2AC3DE",
    "#9ECE6A",
    "#A9B1D6",
    "#BB9AF7",
    "#7AA2F7",
    "#565F89",
    
]

[theme.default]
color = "#89DDFF"
background = "#1F2335"

[theme.completion]
default.background = "#292E42"
default.color = "#3B4261"
selected.background = "#24283B"
selected.color = "#89DDFF"

[theme.timeline]
redacted.color = "#737AA2"

[theme.messages]
code.color = "#A9B1D6"
code.background = "#24283B"
emphasis.color = "#7AA2F7"
strong.color = "#BB9AF7"

[theme.rooms]
default.color = "#565F89"
unread.color = "#A9B1D6"
labels.color = "#7AA2F7"

[theme.windows]
border.color = "#3B4261"
title.color = "#C0CAF5"

[theme.encryption]
icon_encrypted.color = "#9ECE6A"
icon_unencrypted.color = "#FF8349"
icon_unknown.color = "#2AC3DE"

[theme.cmdbar]
error.color = "#FF8349"
